version: "3.8"
services:
  # nest-app:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - mysql-container
  #     - redis-container
  #   ports:
  #     - '3000:3000'
  postgres-dribbble:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /Users/natchen/Downloads/db/postgres-dribbble:/var/lib/postgresql/data
